### ISSUE TITLE
env.target doesn't seem to work

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/hybrid-app-template#10]
![image](https://user-images.githubusercontent.com/2244753/31885028-71e3e232-b7ef-11e7-8f84-0e281bcaf10c.png)

Running the command works, although i get a production zip file. When I look in the zip, the Settings.json file contains the production url, instead of the requested test url.

**Comment by MulderWH** [comment]
Hi Paul, I do not have a settings.json, however in latest package from sprintr I do have an environments.json. In this file the different environments and urls are configured. Hope this helps.

**Comment by Mcpoowl** [comment]
@MulderWH Correct, i have environments.json aswell, with the correct URLS, so when i try to build for the test environment, running npm run package -- --env.target=test I'd expect a zipfile pointing to my test environment, but it still points to Production

**Comment by MulderWH** [comment]
I cannot confirm your issue. I added the test environment to the environments.json, because it was missing. Anyways the output file points to the correct test URL.

**Comment by Mcpoowl** [comment]
@MulderWH So, npm run package -- --env.target=test does give you a test zipfile?

**Comment by MulderWH** [comment]
@Mcpoowl  Yes, I just tried. Then when I open the zipfile I see the settings.json contains the same URL as configured in the environments.json.

**Comment by Mcpoowl** [comment]
@MulderWH interesting. Just tried it at a colleague's it works there aswell.. Not sure what I missed. All the steps seem to make sense:

1) Download zipfile from cloud portal
2) powershell to dir
3) npm install
4) npm run package -- --env.target=test (since this test env is already in my environments.json)

I just tried upgrading npm (since I was @ version 3.11 or something) Now it upgraded to 5.5.1, but now i get an error at 'npm install' in my directory:

![image](https://user-images.githubusercontent.com/2244753/31890566-df4ac84a-b803-11e7-8f4f-97c760aa9709.png)

**Comment by KevinVlaanderen** [comment]
There is indeed an issue with the initial run, which fails if there is no /build folder yet. I'll push a fix later this week, but in the meantime, you could try creating a folder called 'build' manually.

**Comment by Mcpoowl** [comment]
@KevinVlaanderen It's strange that the complete process does work on 3.10.10 (which is included with the LTS version of NodeJS) and upgrading npm gives a npm install error first, and after that the -- --env.target=test parameter isn't passed to webpack
