### ISSUE TITLE
npm install throws error on phonegap prepare

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/hybrid-app-template#11]
In line with #10 I decided to create a new issue, because I can't even to get npm install to run right now.

Facts:

`node -v`

![image](https://user-images.githubusercontent.com/2244753/31897680-68f14f2a-b817-11e7-81ae-5f0a49a2b3a2.png)

`npm -v`

![image](https://user-images.githubusercontent.com/2244753/31897692-77eb57fa-b817-11e7-9808-9a9ddee32e1c.png)

`npm install`

![image](https://user-images.githubusercontent.com/2244753/31897758-a1332502-b817-11e7-8fcf-6e85003a7f9f.png)

Piece of logfile mentioned in `npm install`

`15306 info lifecycle mendix-hybrid-app-template@1.3.1~install: mendix-hybrid-app-template@1.3.1
15307 verbose lifecycle mendix-hybrid-app-template@1.3.1~install: unsafe-perm in lifecycle true
15308 verbose lifecycle mendix-hybrid-app-template@1.3.1~install: PATH: C:\Users\paulk\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\StOReCommMobile\node_modules\.bin;C:\Users\paulk\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\paulk\bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Calibre2;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Users\paulk\AppData\Local\Microsoft\WindowsApps;C:\Users\paulk\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
15309 verbose lifecycle mendix-hybrid-app-template@1.3.1~install: CWD: D:\StOReCommMobile
15310 silly lifecycle mendix-hybrid-app-template@1.3.1~install: Args: [ '/d /s /c', 'npm run init' ]
15311 silly lifecycle mendix-hybrid-app-template@1.3.1~install: Returned: code: 0  signal: null
15312 silly postinstall mendix-hybrid-app-template@1.3.1
15313 info lifecycle mendix-hybrid-app-template@1.3.1~postinstall: mendix-hybrid-app-template@1.3.1
15314 silly prepublish mendix-hybrid-app-template@1.3.1
15315 info lifecycle mendix-hybrid-app-template@1.3.1~prepublish: mendix-hybrid-app-template@1.3.1
15316 info lifecycle mendix-hybrid-app-template@1.3.1~prepare: mendix-hybrid-app-template@1.3.1
15317 verbose lifecycle mendix-hybrid-app-template@1.3.1~prepare: unsafe-perm in lifecycle true
15318 verbose lifecycle mendix-hybrid-app-template@1.3.1~prepare: PATH: C:\Users\paulk\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\StOReCommMobile\node_modules\.bin;C:\Users\paulk\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\paulk\bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Calibre2;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Users\paulk\AppData\Local\Microsoft\WindowsApps;C:\Users\paulk\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
15319 verbose lifecycle mendix-hybrid-app-template@1.3.1~prepare: CWD: D:\StOReCommMobile
15320 silly lifecycle mendix-hybrid-app-template@1.3.1~prepare: Args: [ '/d /s /c', 'cd build && phonegap prepare' ]
15321 silly lifecycle mendix-hybrid-app-template@1.3.1~prepare: Returned: code: 1  signal: null
15322 info lifecycle mendix-hybrid-app-template@1.3.1~prepare: Failed to exec prepare script
15323 verbose stack Error: mendix-hybrid-app-template@1.3.1 prepare: `cd build && phonegap prepare`
15323 verbose stack Exit status 1
15323 verbose stack     at EventEmitter.<anonymous> (C:\Users\paulk\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
15323 verbose stack     at emitTwo (events.js:106:13)
15323 verbose stack     at EventEmitter.emit (events.js:191:7)
15323 verbose stack     at ChildProcess.<anonymous> (C:\Users\paulk\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
15323 verbose stack     at emitTwo (events.js:106:13)
15323 verbose stack     at ChildProcess.emit (events.js:191:7)
15323 verbose stack     at maybeClose (internal/child_process.js:920:16)
15323 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15324 verbose pkgid mendix-hybrid-app-template@1.3.1
15325 verbose cwd D:\StOReCommMobile
15326 verbose Windows_NT 10.0.16299
15327 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\paulk\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
15328 verbose node v6.11.4
15329 verbose npm  v5.5.1
15330 error code ELIFECYCLE
15331 error errno 1
15332 error mendix-hybrid-app-template@1.3.1 prepare: `cd build && phonegap prepare`
15332 error Exit status 1
15333 error Failed at the mendix-hybrid-app-template@1.3.1 prepare script.
15333 error This is probably not a problem with npm. There is likely additional logging output above.
15334 verbose exit [ 1, true ]`

**Comment by Mcpoowl** [comment]
Issue seems to be resolved when working with an older version of npm

npm 3.10.10 DOES work
npm 5.5.1 doesn't

**Comment by KevinVlaanderen** [comment]
As replied on #10 , there is indeed an issue with the initial run, which fails if there is no /build folder yet. I'll push a fix later this week, but in the meantime, you could try creating a folder called 'build' manually.

I do not recommend downgrading npm to v3.

**Comment by isamu-tanaka** [comment]
There is still the same issue existing.
Use Node.js 7.3.0 and npm 3.10.10

**Comment by KevinVlaanderen** [comment]
Hi @isamu-tanaka , we've released a new version of the hybrid app packages. Could you give it another spin?
