### ISSUE TITLE
Latest 1.3.4 version is still pointing to hybrid-app-base 1.7.0

### ISSUE THREAD

**Issue by MulderWH** [mendix/hybrid-app-template#13]
I was trying to create a new build, but still got an old config.xml.mustache file where the phonegap-version was set to cli-7.0.1. 

Anyways I think this happens, because the package-lock.json does not point to the latest 1.7.2 version, which support cli-7.1.0. 

Can you verify?

**Comment by KevinVlaanderen** [comment]
You are absolutely right. I've pushed a new version. It will also be available from the Mendix portal shortly.
