### ISSUE TITLE
Question: with new version I need to use sudo for npm install on Mac

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/hybrid-app-template#17]
Hi,

With the latest release I get an error message from npm install, I need to run with sudo on the Mac. If this is intentional, please mention this on the documentation and on the hybrid app template as well.

With regards,

Marcel

**Comment by mgroeneweg** [comment]
[2018-11-22T07_10_10_893Z-debug.log](https://github.com/mendix/hybrid-app-template/files/2606957/2018-11-22T07_10_10_893Z-debug.log)
Added the log file

**Comment by KevinVlaanderen** [comment]
Hi Marcel.,

Thanks for the feedback. I took a look at the logs, but they do not provide a lot of insight, unfortunately. I also cannot reproduce your issue, making investigation a bit difficult.

From the logs, it is clear that something goes wrong in init.js, which is run as part of `npm run init`, which in turn is called after `npm install`. That module does not do a lot of exciting stuff, but we do use `shelljs` there.

Could you try removing line 63 and below from init.js? I suspect that the call to shell.which is the culprit.

Cheers,
Kevin

**Comment by mgroeneweg** [comment]
Hi Kevin,

That did not help. I deleted the previous attempt and started with a fresh extract of the zip file and deleted the lines from init.js.

I also created support ticket 76907, which contains the phonegap.zip file of my test project

Copied from the terminal window:

Required Phonegap CLI version (minimum): 8.1.1

> @mendix/mendix-hybrid-app-template@3.0.2 prepare /Users/marcelgroeneweg/Downloads/phonegapTestOfflinePhonegap8
> npm run phonegap -- prepare


> @mendix/mendix-hybrid-app-template@3.0.2 phonegap /Users/marcelgroeneweg/Downloads/phonegapTestOfflinePhonegap8
> cd build && phonegap "prepare"

[phonegap] executing 'cordova prepare' ...
Current working directory is not a Cordova-based project.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mendix/mendix-hybrid-app-template@3.0.2 phonegap: `cd build && phonegap "prepare"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @mendix/mendix-hybrid-app-template@3.0.2 phonegap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcelgroeneweg/.npm/_logs/2018-11-22T10_50_42_267Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mendix/mendix-hybrid-app-template@3.0.2 prepare: `npm run phonegap -- prepare`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @mendix/mendix-hybrid-app-template@3.0.2 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcelgroeneweg/.npm/_logs/2018-11-22T10_50_42_318Z-debug.log

[2018-11-22T10_50_42_267Z-debug.log](https://github.com/mendix/hybrid-app-template/files/2607676/2018-11-22T10_50_42_267Z-debug.log)
[2018-11-22T10_50_42_318Z-debug.log](https://github.com/mendix/hybrid-app-template/files/2607677/2018-11-22T10_50_42_318Z-debug.log)

**Comment by luanven** [comment]
@mgroeneweg in terminal run `npm run package` this will webpack all the your files and copy it to the build directory

then run `npm install` again. Phonegap should then correctly prepare your build directory

if the webpack task is not run then the build folder wont have the compiled files that phonegap needs to identify that it is a cordova project.

Hope that helps

**Comment by mgroeneweg** [comment]
@luanven npm run package helped to get npm install to work. This probably needs a little rework in the scripts because npm install is the first step, to bring in all the other stuff. So maybe it can do the first part, then invoke the same function as npm run package and then do the remaining tasks. Or split in multiple separate commands. 

Note that this still leaves #18 unresolved, adding ios platform still fails.

**Comment by KevinVlaanderen** [comment]
I have pushed a new version of the hybrid app template. I added phonegap as a local dependency, instead of requiring it as a global dependency (prepare:all can be used instead, when needed).

Can you confirm that this solves the issues?

**Comment by mgroeneweg** [comment]
Hi @KevinVlaanderen,

I tried but it failed. Please check the support ticket for further details.

With regards,

Marcel

**Comment by KevinVlaanderen** [comment]
Hi Marcel,

It seems you are missing the `pod` command (part of CocoaPods), which is needed to install some iOS phonegap dependencies.

I've updated the prerequisites section of the README to reflect this.

**Comment by KevinVlaanderen** [comment]
The problem turned out to be compounded. The 'pod install' step is needed for the push plugin. However, if you disable the push capability, there will be no Podfile and the platform:ios step would fail. This was an oversight in the tests.
We've released a new version that ignores such failures from 'pod install'

**Comment by mgroeneweg** [comment]
@KevinVlaanderen it works with the latest release.
