### ISSUE TITLE
npm run platform:ios fails with latest hybrid app base release

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/hybrid-app-template#18]
Hi,

I just tried building an app using the new base and template. I downloaded a fresh copy of phonegap.zip. First, I needed sudo for npm install See issue #17 

But npm run platform:ios fails too, also with sudo.

Logfile 2018-11-22T07_20_56_042Z-debug.log has all the nasty details.

As this is for a customer project, please check and advise.

With regards,

Marcel

[2018-11-22T07_10_10_893Z-debug.log](https://github.com/mendix/hybrid-app-template/files/2606951/2018-11-22T07_10_10_893Z-debug.log)
[2018-11-22T07_20_56_042Z-debug.log](https://github.com/mendix/hybrid-app-template/files/2606953/2018-11-22T07_20_56_042Z-debug.log)

**Comment by KevinVlaanderen** [comment]
Hi Marcel,

I've noticed that `npm run platform:ios` can fail when you have not already added the Android platform. This seems to be a problem with the Cordova framework. To work around this, you should make sure that the Android platform was added before running `npm run package:ios`, either by running `npm run platform:all`, or by running `npm run platform:android` beforehand.

If required, you can later remove the android platform by running `npm run platform -- remove android`.

Can you confirm this?

**Comment by mgroeneweg** [comment]
Hi @KevinVlaanderen,

I tried but it failed. Please check the support ticket for further details.

With regards,

Marcel

**Comment by mgroeneweg** [comment]
@KevinVlaanderen it works with the latest release.
