### ISSUE TITLE
Default login page has no styling and does not show login errors.

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/hybrid-app-template#19]
After rebuilding for the latest template release, I noticed that the default login page looks a bit off-color. And it does not show login errors when you enter an unknown userid/password. The starting app... text is left on page too.

The Mendix project is at 7.13.1. I did not specify any custom styling.

![screen shot 2018-11-26 at 15 51 59](https://user-images.githubusercontent.com/6723899/49021858-dfaddc80-f193-11e8-8b8c-36cf9c9837d5.png)

**Comment by smarki** [comment]
Hey @mgroeneweg,
Do you still face this issue?

**Comment by mgroeneweg** [comment]
Hi,

Not with recent app builds and Mx 7.23.x / Mx8

Marcel
