### ISSUE TITLE
Upgrade cordova-android to 7.1.4

### ISSUE THREAD

**Issue by luanven** [mendix/hybrid-app-template#21]
[https://github.com/apache/cordova-plugin-inappbrowser/issues/355](url)

Please upgrade cordova-android to 7.1.4 there is an issue with the inappbrowser on 7.1.2 and 7.1.3. just wasted a day trying to debug this issue

**Comment by jogboms** [comment]
This is no longer valid as Cordova-android has seen an update to `7.1.4`
